package storage

type ISO3886 struct {
	CountryName string `json:"country_name"`
	Alpa2Code   string `json:"alpa_2_code"`
}

var Countres = []ISO3886{
	{"Australia", "AU"}, {"Austria", "AT"},
	{"Azerbaijan", "AZ"}, {"Albania", "AL"},
	{"Algeria", "DZ"}, {"Anguilla", "AI"},
	{"Angola", "AO"}, {"Andorra", "AD"},
	{"Antarctic", "AQ"}, {"Antigua and Barbuda", "AG"},
	{"Netherlands, An lles", "AN"}, {"Argentina", "AR"},
	{"Armenia", "AM"}, {"Aruba", "AW"},
	{"Afghanistan", "AF"}, {"Bahamas", "BS"},
	{"Bangladesh", "BD"}, {"Barbados", "BB"},
	{"Bahrain", "BH"}, {"Belarus", "BY"},
	{"Belize", "BZ"}, {"Belgium", "BE"},
	{"Benin", "BJ"}, {"Bermuda", "BM"},
	{"Bouvet Island", "BV"}, {"Bulgaria", "BG"},
	{"Bolivia", "BO"}, {"Bosnia and Herzegovina", "BA"},
	{"Botswana", "BW"}, {"Brazil", "BR"},
	{"Brunei Darussalam", "BN"}, {"Burkina - Faso", "BF"},
	{"Burundi", "BI"}, {"Bhutan", "BT"},
	{"Vanuatu", "VU"}, {"Vatican(Holy See)", "VA"},
	{"Great Britain (UnitedKingdom)", "GB"}, {"Hungary", "HU"},
	{"Venezuela", "VE"}, {"Virgin Islands, British", "VG"},
	{"Virgin Islands, US", "VI"}, {"American Samoa", "AS"},
	{"East Timor", "TP"}, {"Viet Nam", "VN"},
	{"Gabon", "GA"}, {"Haiti", "HT"},
	{"Guyana", "GY"}, {"Gambia", "GM"},
	{"Ghana", "GH"}, {"Guadeloupe", "GP"},
	{"Guatemala", "GT"}, {"Guinea", "GN"},
	{"Guinea - Bissau", "GW"}, {"Germany", "DE"},
	{"Gibraltar", "GI"}, {"Honduras", "HN"},
	{"Hong Kong", "HK"}, {"Grenada", "GD"},
	{"Greenland", "GL"}, {"Greece", "GR"},
	{"Georgia", "GE"}, {"Guam", "GU"},
	{"Denmark", "DK"}, {"Democratic Republic of the Congo", "CD"},
	{"Djibouti", "DJ"}, {"Dominica", "DM"},
	{"Dominican Republic", "DO"}, {"Egypt", "EG"},
	{"Zambia", "ZM"}, {"Western Sahara", "EH"},
	{"Zimbabwe", "ZW"}, {"Israel", "IL"},
	{"India", "IN"}, {"Indonesia", "ID"},
	{"Jordan", "JO"}, {"Iraq", "IQ"},
	{"Iran", "IR"}, {"Ireland", "IE"},
	{"Iceland", "IS"}, {"Spain", "ES"},
	{"Italy", "IT"}, {"Yemen", "YE"},
	{"Cape Verde", "CV"}, {"Kazakhstan", "KZ"},
	{"Cayman Islands", "KY"}, {"Cambodia", "KH"},
	{"Cameroon", "CM"}, {"Canada", "CA"},
	{"Qatar", "QA"}, {"Kenya", "KE"},
	{"Cyprus", "CY"}, {"Kirghizstan", "KG"},
	{"Kiribati", "KI"}, {"China", "CN"},
	{"Cocos(Keeling) Islands", "CC"}, {"Colombia", "CO"},
	{"Comoros", "KM"}, {"Congo", "CG"},
	{"Costa Rica", "CR"}, {"Cote d Ivoire", "CI"},
	{"Cuba", "CU"}, {"Kuwait", "KW"},
	{"Cook Islands", "CK"}, {"Lao People's Democratic Republic", "LA"},
	{"Latvia", "LV"}, {"Lesotho", "LS"},
	{"Liberia", "LR"}, {"Lebanon", "LB"},
	{"Libyan Arab Jamahiriya", "LY"}, {"Lithuania", "LT"},
	{"Liechtenstein", "LI"}, {"Luxembourg", "LU"},
	{"Mauritius", "MU"}, {"Mauritania", "MR"},
	{"Madagascar", "MG"}, {"Mayotte", "YT"},
	{"Macau (Macao)", "MO"}, {"Macedonia", "MK"},
	{"Malawi", "MW"}, {"Malaysia", "MY"},
	{"Mali", "ML"}, {"Maldives", "MV"},
	{"Malta", "MT"}, {"Marocco", "MA"},
	{"Martinique", "MQ"}, {"Marshall Islands", "MH"},
	{"Mexico", "MX"}, {"Federated States of Micronesia", "FM"},
	{"Mozambique", "MZ"}, {"Moldova", "MD"},
	{"Monaco", "MC"}, {"Mongolia", "MN"},
	{"Montserrat", "MS"}, {"Myanmar", "MM"},
	{"Namibia", "NA"}, {"Nauru", "NR"},
	{"Nepal", "NP"}, {"Niger", "NE"},
	{"Nigeria", "NG"}, {"Netherlands(Holland)", "NL"},
	{"Nicaragua", "NI"}, {"Niue", "NU"},
	{"New Zealand", "NZ"}, {"New Caledonia", "NC"},
	{"Norway", "NO"}, {"Norfolk Island", "NF"},
	{"United Arab mirates", "AE"}, {"Oman", "OM"},
	{"Pakistan", "PK"}, {"Palau", "PW"},
	{"Pales nian Territory(occupied)", "PS"}, {"Panama", "PA"},
	{"Papua New Guinea", "PG"}, {"Paraguay", "PY"},
	{"Peru", "PE"}, {"Pitcairn", "PN"},
	{"Poland", "PL"}, {"Portugal", "PT"},
	{"Puerto Rico", "PR"}, {"Reunion", "RE"},
	{"Christmas Island", "CX"}, {"Russia(Russian Federation)", "RU"},
	{"Rwanda", "RW"}, {"Romania", "RO"},
	{"El Salvador", "SV"}, {"Samoa", "WS"},
	{"San Marino", "SM"}, {"Sao Tomea and Principe", "ST"},
	{"Saudi Arabia", "SA"}, {"Swaziland", "SZ"},
	{"Svalbard and Jan Mayen Islands", "SJ"}, {"St.Helena", "SH"},
	{"Korea(North)", "KP"}, {"Northern Mariana Islands", "MP"},
	{"Seychelles", "SC"}, {"Saint Vincent and the Grenadines", "VC"},
	{"St.Pierre and Miquelon", "PM"}, {"Senegal", "SN"},
	{"Saint Kitts(Christopher) and Nevis", "KN"}, {"Saint Lucia", "LC"},
	{"Singapore", "SG"}, {"Syria", "SY"},
	{"Slovak Republic", "SK"}, {"Slovenia", "SI"},
	{"United States of America", "US"}, {"Solomon Islands", "SB"},
	{"Somali", "SO"}, {"Sudan", "SD"},
	{"Surinam", "SR"}, {"Sierra Leone", "SL"},
	{"Tadjikistan", "TJ"}, {"Thailand", "TH"},
	{"Taiwan", "TW"}, {"Tanzania", "TZ"},
	{"Turks and Caicos Islands", "TC"}, {"Togo", "TG"},
	{"Tokelau", "TK"},
}
